# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:  sjstreeting/pipelines-hugo

pipelines:
   branches:
      master:
        - step: 
                name: Project Upload
                script:
                  - rsync -zrSlh --stats ./ ubuntu@52.214.72.17:/var/www/dataintegrationtool/
        - step:
                name: Set execution permissions
                script:
                 - pipe: atlassian/ssh-run:0.1.4
                   variables:
                     SSH_USER: 'ubuntu'
                     SERVER: '52.214.72.17'
                     COMMAND: 'sudo chmod 777 /var/www/dataintegrationtool/pm2_run_batch_file.sh'

        - step:
               name: Run
               script:
                - pipe: atlassian/ssh-run:0.1.4
                  variables:
                    SSH_USER: 'ubuntu'
                    SERVER: '52.214.72.17'
                    COMMAND: 'sudo bash /var/www/dataintegrationtool/run_batch_file_as_single_command.sh'


