export const SET_FILE_STEPS = 'SET_FILE_STEPS';
export const SET_STREAM_STEPS = 'SET_STREAM_STEPS';
export const SET_CURRENT_STEPS = 'SET_CURRENT_STEPS';
export const SET_ACTIVE_STEP = 'SET_ACTIVE_STEP';
export const SET_FOOTSTEPS = 'SET_FOOTSTEPS';
export const ADD_FOOTSTEP = 'ADD_FOOTSTEP';

export const SET_UPLOAD_TYPE = 'SET_UPLOAD_TYPE';
export const SET_UPLOAD_OBJECTS = 'SET_UPLOAD_OBJECTS';
export const SET_UPLOAD_FILE = 'SET_UPLOAD_FILE';
export const SET_UPLOAD_STREAM = 'SET_UPLOAD_STREAM';
export const SET_CURRENT_SHEET = 'SET_CURRENT_SHEET';
export const SET_RESOURCE = 'SET_RESOURCE';
export const INIT_MAPPINGS = 'INIT_MAPPINGS';
export const SET_MAPPING = 'SET_MAPPING';
export const SET_METADATA = 'SET_METADATA';
