import React, { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { getFormAsyncErrors, getFormSyncErrors, getFormValues, submit } from 'redux-form';
import { Redirect } from 'react-router-dom';

import HeaderContentsFooterTemplate from '../components/templates/HeaderContentsFooterTemplate';
import MetaFormEditor from '../components/organisms/MetaFormEditor';
import { setMetadata } from '../redux/actions/mainActions';
import { METADATA_STEP_NAME } from '../EN_Texts';
import { getUploadMetadata } from '../redux/selectors/mainSelectors';
import ServerSender from '../components/organisms/ServerSender';
import { footstepValidation } from '../redux/selectors/stepsSelectors';
import { ROUTE_MAIN } from '../STEPS_and_routes';

/*************
 * Needs to be done:
 * - in the store.newfile we will put the new csv file generated by the columns that the user has selected
 * - in the handleFinish function bellow we must send the whole store.main to the server
 */
const MetadataAndSendPage = () => {
    const dispatch = useDispatch();
    const form = useSelector(getFormValues(METADATA_STEP_NAME));
    const metadataStore = useSelector(getUploadMetadata);
    const formSyncErrors = useSelector(getFormSyncErrors(METADATA_STEP_NAME));
    const formAsyncErrors = useSelector(getFormAsyncErrors(METADATA_STEP_NAME));
    const isValid =
        (!formSyncErrors || (Object.keys(formSyncErrors).length === 0 && formSyncErrors.constructor === Object)) &&
        (!formAsyncErrors || (Object.keys(formAsyncErrors).length === 0 && formAsyncErrors.constructor === Object));
    const [sending, setSending] = useState(false);
    const handleFinish = cb => {
        dispatch(setMetadata(form));
        setSending(true);
        setTimeout(() => {
            dispatch(submit(METADATA_STEP_NAME));
            setSending(false);
            if (isValid) {
                if (cb) cb(); //go next
            }
        }, 3000);
    };
    const footstepsValid = useSelector(footstepValidation);
    if (footstepsValid)
        return (
            <HeaderContentsFooterTemplate onFinish={handleFinish}>
                <MetaFormEditor initialValues={metadataStore} onSubmit={() => {}} />
                <ServerSender open={sending} />
            </HeaderContentsFooterTemplate>
        );
    else return <Redirect to={ROUTE_MAIN} />;
};

export default MetadataAndSendPage;
